language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t 0rogyy/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true 0rogyy/docker-react-app npm run test -- --coverage

